# Generated by Django 2.1.3 on 2018-11-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='number_of_performances_to_list',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='site',
            name='number_of_songs_to_list',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='song',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='external_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
