# Generated by Django 2.1.3 on 2018-12-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20181127_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='order',
            new_name='display_order',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='number_of_performances_to_list',
            new_name='number_of_performances_to_display',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='number_of_songs_to_list',
            new_name='number_of_songs_to_display',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='order',
            new_name='display_order',
        ),
    ]
