# Generated by Django 2.1.3 on 2018-12-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20181208_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='external_link',
        ),
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default='None', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
